[package]
name = "rust-xray"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
ring = "0.17.8"
rustls-pki-types = "1.8.0"
tokio = {version = "1.40.0", features = ["full"]}
zeroize = "1.8.1"

