syntax = "proto3";

package xray.app.router;
option csharp_namespace = "Xray.App.Router";
option go_package = "github.com/xtls/xray-core/app/router";
option java_package = "com.xray.app.router";
option java_multiple_files = true;

import "common/serial/typed_message.proto";
import "common/net/port.proto";
import "common/net/network.proto";
import "common/geodata/geodat.proto";

message RoutingRule {
  oneof target_tag {
    string tag = 1;
    string balancing_tag = 12;
  }

  string rule_tag = 19;

  repeated xray.common.geodata.DomainRule domain = 2;
  repeated xray.common.geodata.IPRule ip = 10;
  xray.common.net.PortList port_list = 14;
  repeated xray.common.net.Network networks = 13;
  repeated xray.common.geodata.IPRule source_ip = 11;
  xray.common.net.PortList source_port_list = 16;

  repeated string user_email = 7;
  repeated string inbound_tag = 8;
  repeated string protocol = 9;

  map<string, string> attributes = 15;

  repeated xray.common.geodata.IPRule local_ip = 17;
  xray.common.net.PortList local_port_list = 18;

  xray.common.net.PortList vless_route_list = 20;

  repeated string process = 21;
  WebhookConfig webhook = 22;

  // List of operating systems for matching the one Xray itself is running on.
  repeated string local_os = 23;
}

message WebhookConfig {
  string url = 1;
  uint32 deduplication = 2;
  map<string, string> headers = 3;
}

message BalancingRule {
  string tag = 1;
  repeated string outbound_selector = 2;
  string strategy = 3;
  xray.common.serial.TypedMessage strategy_settings = 4;
  string fallback_tag = 5;
}

message StrategyWeight {
  bool regexp = 1;
  string match = 2;
  float value = 3;
}

message StrategyLeastLoadConfig {
  repeated StrategyWeight costs = 2;
  repeated int64 baselines = 3;
  int32 expected = 4;
  int64 maxRTT = 5;
  float tolerance = 6;
}

message Config {
  enum DomainStrategy {
    AsIs = 0;
    reserved 1;
    IpIfNonMatch = 2;
    IpOnDemand = 3;
  }
  DomainStrategy domain_strategy = 1;
  repeated RoutingRule rule = 2;
  repeated BalancingRule balancing_rule = 3;
}
